### ISSUE TITLE
Vagrant Share doesn't share SSH connection

### ISSUE THREAD

**Issue by nnlkcncff** [hashicorp/vagrant-share#7]
### Vagrant version

```shell
vagrant --version
Vagrant 2.3.7
```

### Vagrant Share, Xcode and ngrok versions

```shell
xcode-select --version
xcode-select version 2397

vagrant plugin vagrant-share --version
Vagrant 2.3.7

ngrok --version
ngrok version 3.3.1
```

### Host operating system

```shell
sw_vers
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
```

### Provider and plugin versions

```shell
prlctl --version
prlctl version 18.1.0 (53311)

vagrant plugin vagrant-parallels --version
Vagrant 2.3.7
```

### Guest operating system

```shell
cat /etc/almalinux-release
AlmaLinux release 9.1 (Lime Lynx)
```

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vagrant.plugins = {"vagrant-parallels" => {"version" => "2.4.0"}}

  config.vm.box = "bento/almalinux-9"
  config.vm.box_version = "202303.13.0"

  config.vm.provider "parallels" do |prl|
    prl.customize "post-import", ["set", :id,
      "--cpus", "2", "--hypervisor-type", "parallels", "--nested-virt", "on",
      "--memsize", "4096"
    ]
  end

  config.vm.network "forwarded_port", guest: 22, host: 50022
end
```

### Debug output

https://gist.github.com/nnlkcncff/59baa03a559d96efb936399da056eceb

### Expected behavior

https://developer.hashicorp.com/vagrant/docs/share/ssh

### Actual behavior

```shell
vagrant share --ssh --ssh-no-password
==> default: Detecting network information for machine...
    default: Local machine address: 10.211.55.28
    default: An HTTP port couldn't be detected! Since SSH is enabled, this is
    default: not an error. If you want to share both SSH and HTTP, please set
    default: an HTTP port with `--http`.
    default:
==> default: Generating new SSH key...
/Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/command/ngrok/share.rb:438:in `configure_ssh_connect': undefined local variable or method `ssh_port' for #<VagrantPlugins::Share::Command::Share:0x000000010fd5e700 @argv=["--ssh", "--ssh-no-password"], @env=#<Vagrant::Environment: /Users/nnlkcncff/Desktop/vagrant>, @logger=#<Log4r::Logger:0x000000010fd9caf0 @fullname="vagrant::share::command::share", @outputters=[], @additive=true, @name="share", @path="vagrant::share::command", @parent=#<Log4r::RootLogger:0x000000010baf9a68 @level=0, @outputters=[]>, @level=0, @trace=false>, @options={:use_key_once=>false, :disable_http=>false, :ssh=>true, :ssh_no_password=>true, :ssh_flag=>true, :ssh_username=>"vagrant", :ssh_port=>50022}> (NameError)

                "addr" => ssh_port
                          ^^^^^^^^
Did you mean?  ssh_password
	from /Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/command/ngrok/share.rb:74:in `block in start_share'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/command/ngrok/share.rb:34:in `start_share'
	from /Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/command/share.rb:122:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/bin/vagrant:248:in `<main>'

vagrant share --ssh
==> default: Detecting network information for machine...
    default: Local machine address: 10.211.55.28
    default: An HTTP port couldn't be detected! Since SSH is enabled, this is
    default: not an error. If you want to share both SSH and HTTP, please set
    default: an HTTP port with `--http`.
    default:
==> default: Generating new SSH key...
    default: Please enter a password to encrypt the key:
    default: Repeat the password to confirm:
    default: Inserting generated SSH key into machine...
    default: Local HTTP port: disabled
    default: Local HTTPS port: disabled
    default: SSH Port: 50022
==> default: Creating Vagrant Share session...
<internal:/opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick/https (LoadError)
	from <internal:/opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/helper/api.rb:21:in `start_api'
	from /Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/command/ngrok/share.rb:454:in `setup_share_api'
	from /Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/command/ngrok/share.rb:118:in `block in start_share'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/command/ngrok/share.rb:34:in `start_share'
	from /Users/nnlkcncff/.vagrant.d/gems/3.1.4/gems/vagrant-share-2.0.0/lib/vagrant-share/command/share.rb:122:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.3.7/bin/vagrant:248:in `<main>'
```

### Steps to reproduce

1. Install Parallels Desktop, Vagrant, Vagrant Share, ngrok
2. Create Vagrantfile and run `vagrant share --ssh` or `vagrant share --ssh --ssh-no-password`

**Comment by lingjhf** [comment]
vagrant plugin install webrick
